server {
    listen 80;
    
    server_name localhost;

    # Ruta  Angular de archivos compilados 
    root /var/www/tp-final-daw/frontend/dist/frontend/browser;
    index index.html;

    # Configuración para que Angular funcione bien 
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy Inverso para el Backend (NestJS)
    location /api/ {
        proxy_pass http://localhost:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}